snipe.target_sets = {
	pvp = {
		-- twink gear
		{ g=20, "scouting gloves of the monkey", "+4 agility", "+4 stamina" },
		{ g=10, "wrangler's wristbands of the monkey", "+3 agility", "+3 stamina" },
		{ g=5, "wrangler's wristbands of stamina", "+5 stamina" },
		{ g=20, "shadowfang" },
		{ g=10, "sentry cloak" },
		{ g=10, "feet of the lynx" },
		{ g=5, "mindthrust bracers" },
		{ g=3, "magefist gloves" },
		{ g=3, "tree bark jacket" },
		{ g=2, "keller's girdle" },
		{ g=3, "black widow ring" },
		{ g=3, "darkweave breeches" },
		{ g=3, "night reaver" },
		{ g=3, "assassin's blade" },
		{ g=3, "lil timmy's peashooter" },
		{ g=1, s=50, "redbeard crest" },
		{ g=2, s=50, "meadow ring", "+5 agility" },
		{ g=2, s=50, "meadow ring", "+3 agility", "+3 stamina" },
		{ g=4, "meadow ring", "+1 agility", "+1% dodge" },
		{ g=3, "twisted chanter's staff" },
		{ g=3, "silver-linked footguards" },
		{ g=3, "thorbia gauntlets" },

		{ g=9, "tigerstrike mantle" },
		{ g=6, "pathfinder hat of the monkey", "+9 agility", "+9 stamina" },
		{ g=4, "forest tracker epaulets" },
		{ g=3, "ironweaver" },
		{ g=3, "river pride choker" },
		{ g=3, "pugilist bracers" },
		{ g=3, "thunderbrow ring" },
		{ g=3, "plains ring" },
		{ g=3, "frostreaver crown" },
		{ g=3, "starfaller" },
		{ g=4, "zealot blade" },
		
		{ g=40, "pendulum of doom" },
		{ g=30, "staff of jordan" },
		
		{ g=5, "blanchard's stout" },
		{ g=40, "kang the decapitator" },
		{ g=20, "bloodrazor" },
		{ g=10, "wyrmslayer spaulders" },
		{ g=10, "hydralick armor" },
		{ g=10, "wall of the dead" },

		-- endgame gear
		{ g=20, "devilsaur gauntlets" },
		{ g=40, "devilsaur leggings" },
		{ g=30, "teebu's blazing longsword" },
		{ g=50, "maiden's circle" },
		{ g=30, "medallion of grand marshal morris" },
		{ g=50, "alcor's sunrazor" },
		{ g=50, "freezing band" },
		{ g=30, "krol blade" },
		{ g=30, "stockade pauldrons" },
		{ g=40, "flarecore leggings" },
		{ g=40, "corehound belt" },
		{ g=15, "felcloth gloves" },
		{ g=50, "nightfall" },
		
		{ g=20, "head", "cloth", "+41 shadow spell damage" },
		{ g=20, "shoulder", "cloth", "+30 shadow spell damage" },
		{ g=10, "back", "cloth", "+21 shadow spell damage" },
		{ g=10, "wrist", "cloth", "+21 shadow spell damage" },
		{ g=20, "feet", "cloth", "+30 shadow spell damage" },
		{ g=30, "wand", "+23 shadow spell damage" },
		{ g=20, "wand", "+21 shadow spell damage" },
		
		{ g=20, "head", "cloth", "+41 frost spell damage" },
		{ g=20, "shoulder", "cloth", "+30 frost spell damage" },
		{ g=10, "back", "cloth", "+21 frost spell damage" },
		{ g=10, "wrist", "cloth", "+21 frost spell damage" },
		{ g=20, "feet", "cloth", "+30 frost spell damage" },
		{ g=30, "wand", "+23 frost spell damage" },
		{ g=20, "wand", "+21 frost spell damage" },
		
		{ g=30, "wand", "+33 healing spells" },
		
		-- materials, recipes and consumables
		{ g=4, "mooncloth" },
		{ g=40, "formula: enchant weapon - crusader" },
		{ g=100, "recipe: flask of supreme power" },
		{ g=100, "recipe: flask of the titans" },
		{ g=100, "recipe: flask of distilled wisdom" },
		{ g=10, "recipe: greater fire protection potion" },
		{ g=5, "schematic: discombobulator ray" },
		{ g=20, "black lotus" },
		{ g=5, "arcane crystal" },
		{ g=5, "righteous orb" },
		{ s=10, "elemental fire" },
	--	{ g=1, "essence of air" },
	--	{ g=1, "essence of earth" },
	--	{ g=1, "essence of water" },
		{ g=3, "devilsaur leather" },
	--	{ g=2, "core leather" },
	--	{ g=2, "nexus crystal" },
	--	{ g=1, "dark rune" },
	--	{ s=10, "grave moss" },
	--	{ s=20, "winterfall e'ko" },
	--	{ g=10, "fiery core" },
	--	{ g=10, "lava core" },

		{ g=30, "flask of the titans" },
		{ g=30, "flask of supreme power" },
		{ g=30, "flask of distilled wisdom" },
	--	{ s=50, "greater fire protection potion" },
	--	{ g=2, "greater shadow protection potion" },
	--	{ g=1, "greater arcane elixir" },
	--	{ g=1, "elixir of shadow power" },
	--	{ g=3, "elixir of the mongoose" },
	--	{ g=1, s=50, "winterfall firewater" },
		
		-- misc
		{ c=30, "feathered arrow" },
		{ s=30, "fused wiring" },
		{ g=2, "traveler's backpack" },
	},
	pve = {
		-- twink gear
		{ g=7, "hook dagger", "+6 fire spell damage" },
		{ g=5, "wrangler's wristbands of the monkey", "+3 agility", "+3 stamina" },
		{ g=12, "shadowfang" },
	},
	kronos = {
		{ g=1, "scouting gloves of the monkey", "+4 agility", "+4 stamina" },
		{ g=1, "wrangler's wristbands of the monkey", "+3 agility", "+3 stamina" },
		-- { g=3, "hook dagger of fiery wrath", "+4 fire spell damage" },
		-- { g=3, "greenweave sash of fiery wrath", "+9 fire spell damage" },
		-- { g=3, "shimmering sash of fiery wrath", "+9 fire spell damage" },
		-- { g=3, "greenweave bracers of fiery wrath", "+6 fire spell damage" },
		{ g=3, "pagan mitts of fiery wrath", "+9 fire spell damage" },
		-- { g=1, "watcher's cape", "+7 fire spell damage" },
		-- { g=1, "sentry's cape", "+7 fire spell damage" },
		-- { g=1, "superior cloak", "+7 fire spell damage" },
		-- { g=3, "shimmering trousers of fiery wrath", "+11 fire spell damage" },
	}
}